### ISSUE TITLE
Unable to resolve module `buffer` from `xxx/xxx`: Module does not exist in the module map

### ISSUE THREAD

**Issue by Jancat** [crypto-browserify/sha.js#54]
`safe-buffer` package issue?

My node is `v9.2.1`

**Comment by fanatid** [comment]
Please provide more info =\
How you install it, how you use it.

**Comment by Jancat** [comment]
```
yarn add sha.js

import shajs from 'shajs'
shajs('sha256').update('42').digest('hex')
```

Than it throws the error: 

Unable to resolve module `buffer` from `./node-modules/safe-buff/index.js`: Module does not exist in the module map

**Comment by Benjamin-Dobell** [comment]
There's two problems at play here:

1. For some reason this project _doesn't_ have a runtime dependency on `buffer`, when it should.

It's listed in `devDependencies` instead, which is incorrect.

I think it's an attempt to make this project Node compatible, because Node comes with a built-in 'buffer'. However, seems as this project is specifically designed to target browsers that doesn't seem to make a heap of sense.

Given we're specifically targeting browsers there's actually no reason to use `safe-buffer` at all, just go ahead and use `buffer` directly.

2. @Jancat, a problem with your setup.

I'm assuming you're using Rollup here. [rollup-plugin-node-resolve](https://github.com/rollup/rollup-plugin-node-resolve) has some really weird [default behaviour when targeting a browser](https://github.com/rollup/rollup-plugin-node-resolve/blob/902c84881b24178aecabea3041db6ecd2e4895f6/src/index.js#L16).

In the case of a browser there's no such thing as built-ins, the setting should really be `false` if you're targeting a browser. You need to update your `rollup.config.js` to look like:

```javascript
import nodeResolve from 'rollup-plugin-node-resolve';

/* ... */

export default {
  /* ... */
  plugins: [
    nodeOptions({
      /* ... */
      preferBuiltins: false
    }),
    /* ... */
  ],
  /* ... */
}
```

**Comment by dcousens** [comment]
> For some reason this project doesn't have a runtime dependency on buffer, when it should.

@Benjamin-Dobell the project depends on `safe-buffer`,  how `buffer` is resolved in that package... is potentially frustrating,  but,  it was better than trying to resolve that issue everywhere else.

Maybe open the issue there?

**Comment by Benjamin-Dobell** [comment]
@dcousens Is this package meant to run inside Node?

Because if not, I'd suggest replacing the `safe-buffer` dependency with a direct dependency on `buffer`. `safe-buffer` is just an abstraction that allows a project to be compatible with both Node and browser; if this project isn't targeting Node then the abstraction is not necessary.

**Comment by dcousens** [comment]
@Benjamin-Dobell it doesn't *not* target Node?
Whether it should,  is probably up for discussion,  but the same question exists for all of the implementations in https://github.com/crypto-browserify .

In the past,  several were targeting Node to support newer APIs in older versions,  but,  that may not be the case now...

**Comment by Benjamin-Dobell** [comment]
Fair enough 👍

**Comment by dcousens** [comment]
@Benjamin-Dobell up to you if you want to chase that rabbit

**Comment by scscgit** [comment]
> @dcousens I'd suggest replacing the `safe-buffer` dependency with a direct dependency on `buffer`.

Bump, a dependency issue still occurs (e.g. in latest Nuxt 3 that uses Vite instead of Webpack). There is an open PR since 2021 at https://github.com/feross/safe-buffer/pull/33...
